---
name: ko20
version: "0.4"
summary: "Free and open source office suite for Linux with O365 UX."
description: "Highly unstable version of O20 written in QtQuick."
grade: devel
confinement: strict
base: core18
architectures:
  - amd64

apps:
    ko20:
        command: kf5-launch $SNAP/usr/bin/ko20
        common-id: io.gitlab.ko20.desktop
        plugs:
          - browser-support
          - home
          - kde-frameworks-5-plug
          - pulseaudio
          - opengl
          - unity7
          - x11

    ink:
        command: kf5-launch $SNAP/usr/bin/ko20 app:ink
        common-id: io.gitlab.ko20.ink.desktop
        plugs:
          - browser-support
          - home
          - kde-frameworks-5-plug
          - pulseaudio
          - opengl
          - unity7
          - x11

plugs:
    kde-frameworks-5-plug:
        interface: content
        content: kde-frameworks-5-core18-all 
        default-provider: kde-frameworks-5-core18
        target: kf5

parts:
    o20base:
        plugin: cmake
        source-type: git
        source: https://gitlab.com/abstractsoftware/ko20-core.git
        #source-tag: '0.2'

        build-packages: 
            - build-essential
            - libegl1-mesa-dev
            - sonnet-plugins

        build-snaps: 
            - kde-frameworks-5-core18-sdk

        stage-packages:
            - hunspell-en-us
            - hunspell-de-de
            - hunspell-fr
            - hunspell-es
            - hunspell-ru
            - hunspell-cs

        configflags:
            - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
            - "-DCMAKE_INSTALL_PREFIX=/usr"
            - "-DCMAKE_BUILD_TYPE=Release"
            - "-DENABLE_TESTING=OFF"
            - "-DBUILD_TESTING=OFF"
            - "-DINSTALL_FONT=TRUE"
            - "-DKDE_SKIP_TEST_SETTINGS=ON"

    kde-frameworks-5-env:
        plugin: dump
        source: https://github.com/apachelogger/kf5-snap-env.git
